---
title: "04_analytic_data"
author: "Jagadeesh Puvvula"
date: "2026-03-10"
output: pdf_document
---

#12Y BASC outcome data (242)
```{r}
basc_prt_out<- read_sas("~/Documents/data/outcomes.sas7bdat") |>
  clean_names() |>
  select(1, 2, starts_with("basc")) |>
  filter(visit == "P4") |>
  select(c(1,basc_inz))

basc_chld_out<- read_sas("~/Documents/data/basc_child_add.sas7bdat") |>
  clean_names() |>
  select(1, 2, starts_with("basc")) |>
  filter(visit == "P4") |>
  select(c(1,basc_child_inz_gc_t))
```

#imputed covariate data 
```{r}
cov<- read_csv("~/Documents/k99_home/data/covariate_imputation.csv") |>
  filter(subject_id %in% basc_out$subject_id) |> clean_names() |>
  mutate(parity_n = ceiling(parity_n)) |>
  mutate(
    parity_n = case_when(
      parity_n == 0 ~ "0",
      parity_n == 1 ~ "1",
      parity_n > 1  ~ "gt1",
      TRUE ~ NA_character_
    ),
    parity_n = factor(parity_n, levels = c("0", "1", "gt1"))
  )|>
  mutate(across(where(is.character), as.factor))

#cotinine
cotinine <- read_csv("~/Documents/k99_home/data/exposure_impu/imputed_exposures.csv") |>
    filter(exposure == "cotinine") |>
    mutate(
        analyte = str_split_fixed(analyte_visit, "_", 2)[,1],
        visit   = str_split_fixed(analyte_visit, "_", 2)[,2]
    ) |>
    select(subject_id, analyte, visit, result)

# Create average rows
avg_rows <- cotinine |>
    group_by(subject_id, analyte) |>
    summarise(
        result = mean(result, na.rm = TRUE),
        visit = "avg",
        .groups = "drop"
    )

# Combine visit-level and average rows
cotinine <- bind_rows(cotinine, avg_rows) |>
    mutate(subject_id = as.factor(subject_id),
           exposure = "cotinine") 
  
```

#exposure markers - PBDEs (230)
```{r}
pbde_df <- haven::read_sas("~/Documents/data/pbde.sas7bdat") |> clean_names() |>
  mutate(across(any_of(c("subject_id", "visit", "analyte_code")), factor),
                across(contains("flg_lod"), factor)) |>
  rename(flg_lod = flg_lod_lp,
         result = result_lp) |>
  select(c(subject_id, visit, analyte_code, result, flg_lod, analyte_lod_lp)) |>
  filter(visit %in% c("16W", "26W")) |>
  mutate(result = if_else(flg_lod == "1", analyte_lod_lp/sqrt(2), result)) |>
  drop_na(result) |>
  group_by(subject_id, analyte_code) |>
  summarise(
    result = if (n_distinct(visit) == 2) {
      mean(result, na.rm = TRUE)
    } else {
      result[1]
    },
    .groups = "drop"
  ) |>
  filter(subject_id %in% basc_out$subject_id) |> clean_names() |>
  rename(analyte = analyte_code) |>
  mutate(
    exposure = "PBDE",
    visit = "avg"
  )
```

#exposure markers - OPE and Phthalates
```{r}
ur_sg<- read_sas("~/Documents/data/fr.sas7bdat") |> clean_names() |>
  select(c(1,2,11)) |>
  filter(visit %in% c("16W", "26W")) |>
  distinct() |>
  filter(subject_id %in% basc_out$subject_id)

#12 participants with missing SG were imputed using the mean SG for that visit.
ope_phth <- read_csv("~/Documents/k99_home/data/exposure_impu/imputed_exposures.csv") |>
  filter(exposure != "cotinine") |>
  mutate(
    analyte = str_replace(analyte_visit, "_[^_]+$", ""),
    visit   = str_extract(analyte_visit, "[^_]+$")
  ) |>
  left_join(ur_sg, by = c("subject_id", "visit")) |>
  group_by(visit) |>
  mutate(
    specific_gravity = if_else(
      is.na(specific_gravity),
      median(specific_gravity, na.rm = TRUE),
      specific_gravity
    ),
    result_sg_adj = if_else(
      specific_gravity == 1,
      NA_real_,
      result * ((median(specific_gravity, na.rm = TRUE) - 1) / (specific_gravity - 1))
    )
  ) |>
  ungroup() |>
  select(subject_id, exposure, analyte, visit, result_sg_adj)

# Create average rows
avg_rows <- ope_phth |>
  group_by(subject_id, exposure, analyte) |>
  summarise(
    result_sg_adj = mean(result_sg_adj, na.rm = TRUE),
    visit = "avg",
    .groups = "drop"
  )

# Combine visit-level and average rows
ope_phth <- bind_rows(ope_phth, avg_rows) |>
  mutate(subject_id = as.factor(subject_id)) |>
  rename(result = result_sg_adj)
```

#join all exposures
```{r}
exposures <- bind_rows(pbde_df, ope_phth, cotinine) 
```

#export analytic data
```{r}
save(basc_out, cov, exposures, file = "~/Documents/k99_home/data/analytic_data_to join.RData")
```

#final data for analysis
```{r}
exp_wide<- exposures |> 
   select(-exposure) |>
  pivot_wider(names_from = c(analyte, visit), values_from = result)

dat_full <- basc_out |>
  mutate(subject_id = as.factor(subject_id)) |>
  left_join(cov |> mutate(subject_id = as.factor(subject_id)), by = "subject_id") |>
  left_join(exp_wide, by = "subject_id")

save(dat_full, file = "~/Documents/k99_home/data/analytic_data_for_analysis.RData")
write_csv(dat_full, "~/Documents/k99_home/data/analytic_data_for_analysis.csv")
```

